spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://temp-sql.cqoyz1uobynz.ap-northeast-2.rds.amazonaws.com:3306/oMo?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: create

# jwt.secret.key? ?? 256bit ????? ???.
jwt:
  secret:
    key: 9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@

tmdb:
  key: 8428c3738bcfa2273cff43bbce07205c
